language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
env:
  - LOWEST=0
before_script:
  - composer self-update
  - if [[ $LOWEST = 0 ]]; then composer require satooshi/php-coveralls mmoreram/php-formatter --prefer-dist; fi
  - if [[ $LOWEST = 1 ]]; then composer require satooshi/php-coveralls mmoreram/php-formatter --prefer-dist --prefer-lowest; fi
script:
  # - php ./vendor/phpunit/phpunit/phpunit
  - php ./vendor/phpunit/phpunit/phpunit --coverage-clover=build/logs/clover.xml
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload  --format=php-clover build/logs/clover.xml
  - php ./vendor/bin/coveralls -v
notifications:
  email:
    - dev@dankempster.co.uk
matrix:
  allow_failures:
    - php: hhvm
  include:
    # Build against lowest dependancies
    - php: 5.4
      env: LOWEST=1
  fast_finish: true
branches:
  only:
    - develop
    - master
